---------------------------- DRAWN2CODE GENERATED CODE -------------------------
-- This code is automatically generated by Drawn2Code Designer (version 1.48). 
-- As you make changes to your design, the code here will update automatically! 
--> * Edits you make in THIS CODE WINDOW ARE NOT SYNCED to your D2C design * <--
-- Notes:
-- Set the project folder with the "folder" button in the generated code window.
-- Save this code to a "main.lua" file (in the project folder) using the "save"
--   button in the generated code window.
-- Simple "config.lua" & "build.settings" files are created if not present.
-- Design File: "Cowboy Shootout.d2c"
--------------------------------------------------------------------------------


-- Multiline Comment
--[[Cowboy Shootout
Blake Moore
Juan De Haro
Kimi Green
Xinxing Wang
Ziqing Yu
--]]

-- image "CowboyBG.png"
Obj1 = display.newImageRect( "CowboyBG.png", 328, 480 )
Obj1.x = 160
Obj1.y = 240
Obj1.id = "Obj1"

-- Display Constants
cx, cy = display.contentCenterX, display.contentCenterY
cw, ch = display.contentWidth, display.contentHeight

-- adjusts background to fit to content
Obj1.x = cx
Obj1.y = cy
Obj1.height = 1.2 * ch
local widget = require "widget"
display.setStatusBar( display.HiddenStatusBar )

-- load sound effect: 9_mm_gunshot-mike-koenig-123.wav
Obj54 = audio.loadSound("9_mm_gunshot-mike-koenig-123.wav")

-- load sound effect: Gun_Cocking_Fast-Mike_Koenig-465593588.wav
Obj55 = audio.loadSound("Gun_Cocking_Fast-Mike_Koenig-465593588.wav")

-- load sound effect: Male Grunt-SoundBible.com-68178715.wav
Obj56 = audio.loadSound("Male Grunt-SoundBible.com-68178715.wav")

-- load background music: Western Title [LOOP].wav
Obj67 = audio.loadStream("Western Title [LOOP].wav")

-- play audio on channel 1-32 (select channel 0 for the default):
Obj68 = audio.play( Obj67, { loops = -1, })

Obj78_options = {
  text = " ",
  x = 160,
  y = 91,
  width = 327,
  height = 100,
  font = "SnapITC-Regular",
  fontSize = 26,
  align = "center",
}
Obj78 = display.newText( Obj78_options )
Obj78.id = "Obj78"
Obj78:setTextColor(0.77, 0.11, 0.14, 1.0)

Obj79_options = {
  text = "Cowboy Shootout",
  x = 160,
  y = 90,
  width = 327,
  height = 47,
  font = "SnapITC-Regular",
  fontSize = 32,
  align = "center",
}
Obj79 = display.newText( Obj79_options )
Obj79.id = "Obj79"
Obj79:setTextColor(0.77, 0.11, 0.14, 1.0)

Obj6_options = {
  text = "Credits:\n\n\nMobile developers:\n\nBlake Moore\nKimi Green\nJuan De Haro\nXinxing Wang \nZiqing Yu\n\nMusic:\nChris Waters",
  x = 163,
  y = 790,
  width = 246,
  height = 500,
  font = "SnapITC-Regular",
  fontSize = 24,
  align = "center",
}
Obj6 = display.newText( Obj6_options )
Obj6.id = "Obj6"

Obj100_options = {
  text = " ",
  x = 140,
  y = -20,
  width = 127,
  height = 20,
  font = "HelveticaNeue-Bold",
  fontSize = 16,
  align = "left",
}
Obj100 = display.newEmbossedText( Obj100_options )
Obj100.id = "Obj100"
Obj100:setTextColor(0.77, 0.11, 0.14, 1.0)

Obj102_options = {
  text = " ",
  x = 173,
  y = 0,
  width = 193,
  height = 20,
  font = "HelveticaNeue-Bold",
  fontSize = 16,
  align = "left",
}
Obj102 = display.newText( Obj102_options )
Obj102.id = "Obj102"
Obj102:setTextColor(0.77, 0.11, 0.14, 1.0)

-- fn to handle button press on Obj12
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj12
function Obj12OnPressHandler( event )

  -- Obj14: default button event support
  transition.to(Obj6, {delay = 1000, time = 10000, x = 160, y = -250})
  
  -- resets credits location
  Obj6.x = 163
  Obj6.y = 790
  Obj33 = transition.to(MenuGroup, {time=1000, alpha=0.0})
  Obj60 = transition.to(MenuGroup, {time=1000, delay=12000, alpha=1.0})

end


-- remember to move button image resources into your project folder!
Obj12 = widget.newButton({
  x = 160,
  y = 313,
  width = 200,
  height = 114,
  id = "Obj12",
  label = "",
  labelAlign = "center",
  font = "Roboto-Light",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "CreditsButton.png",
  overFile = "CreditsButton.png",
  onPress = Obj12OnPressHandler,
})

-- image "dead bandido.png"
Obj97 = display.newImageRect( "dead bandido.png", 392, 303 )
Obj97.x = 169
Obj97.y = 368
Obj97.id = "Obj97"
Obj97.alpha = 0.0

-- image "dead outlaw.png"
Obj98 = display.newImageRect( "dead outlaw.png", 392, 303 )
Obj98.x = 169
Obj98.y = 368
Obj98.id = "Obj98"
Obj98.alpha = 0.0

-- image "dead raggedy.png"
Obj99 = display.newImageRect( "dead raggedy.png", 392, 303 )
Obj99.x = 169
Obj99.y = 368
Obj99.id = "Obj99"
Obj99.alpha = 0.0

-- image "Bandido.png"
Obj21 = display.newImageRect( "Bandido.png", 392, 303 )
Obj21.x = 169
Obj21.y = 368
Obj21.id = "Obj21"
Obj21.isVisible = false

-- image "Outlaw.png"
Obj81 = display.newImageRect( "Outlaw.png", 392, 303 )
Obj81.x = 169
Obj81.y = 368
Obj81.id = "Obj81"
Obj81.isVisible = false

-- image "Raggedy.png"
Obj93 = display.newImageRect( "Raggedy.png", 392, 303 )
Obj93.x = 169
Obj93.y = 368
Obj93.id = "Obj93"
Obj93.isVisible = false

-- fn to handle button press on Obj15
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj15
function Obj15OnPressHandler( event )

  -- Obj66: setup
  -- randomize random number generator
  math.randomseed(os.time( ))
  
  -- user variable setup
  countShield = 0
  countShoot = 0
  countAmmo = 0
  
  -- computer variable setup
  enemyShield = 0
  enemyShoot = 0
  enemyAmmo = 0
  
  -- game has been started
  gameisRunning = true
  gameOver = false
  
  -- character setup
  user = {name = "Hombre", answer = "", lives = 3}
  opponent = {name = "", answer = "", lives = 3}
  
  -- reset alphas
  Obj21.alpha = 1
  Obj81.alpha = 1
  Obj93.alpha = 1
  Obj97.alpha = 0
  Obj98.alpha = 0
  Obj99.alpha = 0

  -- Obj17: default button event support
  -- starts the game
  gameisRunning = true
  print("You have started the game")
  
  -- moves clouds if game is running
  if gameisRunning then
     CloudsGroup.isVisible = true
  -- resets clouds location on start
     CloudsGroup.x = 0
     CloudsGroup.y = 0
     Obj61 = transition.to(CloudsGroup, {time=200000, x=-500})
     Obj78.text = " "
     gameOver = false
  end
  Obj35 = transition.to(MenuGroup, {time=1000, alpha=0.0})
  Obj34 = transition.to(GameGroup1, {time=1000, delay=800, alpha=1.0})

  -- Obj80: randomize enemy character
  Computer = math.random (1,3)
  
  if gameisRunning then
      if Computer == 1 then
  
         Obj21.isVisible = true
         opponent.name = "Bandido"
         Obj97.isVisible = true
         Obj81.isVisible = false
         Obj98.isVisible = false
         Obj93.isVisible = false
         Obj99.isVisible = false
  
  elseif Computer == 2 then
  -- Outlaw
         Obj21.isVisible = false
         Obj97.isVisible = false
         Obj81.isVisible = true
         opponent.name = "Outlaw"
         Obj98.isVisible = true
         Obj93.isVisible = false
         Obj99.isVisible = false
  
  elseif Computer == 3 then
  
         Obj21.isVisible = false
         Obj97.isVisible = false
         Obj81.isVisible = false
         Obj98.isVisible = false
         Obj93.isVisible = true
         opponent.name = "Raggedy Carlson"
         Obj99.isVisible = true
  
  end;end
  
  print ("Your opponent is... "..opponent.name.."!")
  Obj78.text = "Your opponent is... "..opponent.name.."!"
  Obj102.text = opponent.name..": "..opponent.lives.." Lives"
  Obj100.text = user.name..": "..user.lives.." Lives"

  -- Obj88: disable gun
  if gameisRunning then
  -- disables touch/tap events on gun
     Obj86.isVisible = true
     Obj86:addEventListener("tap", doNothing)
     Obj86:addEventListener("touch", doNothing)
  end

end


-- remember to move button image resources into your project folder!
Obj15 = widget.newButton({
  x = 160,
  y = 178,
  width = 200,
  height = 114,
  id = "Obj15",
  label = "",
  labelAlign = "center",
  font = "Roboto-Light",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "StartButton.png",
  overFile = "StartButton.png",
  onPress = Obj15OnPressHandler,
})

Obj22 = display.newRoundedRect(159, 480, 341, 100, 16)
Obj22.id = "Obj22"
Obj22:setFillColor(0.4, 0.2, 0.0, 1.0)

Obj120_options = {
  text = "OUT OF AMMO",
  x = 264,
  y = 516,
  width = 87,
  height = 13,
  font = "HelveticaNeue",
  fontSize = 11,
  align = "center",
}
Obj120 = display.newText( Obj120_options )
Obj120.id = "Obj120"

-- fn to handle button press on Obj23
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj23
function Obj23OnPressHandler( event )

  -- Obj25: default button event support
  -- Reload button listener
  if gameisRunning then
     print("You have loaded your gun")
     -- keeps track of ammo
     countAmmo = countAmmo + 1
     print ("Ammo = "..countAmmo)
     if countAmmo == 0 then
        Obj120.text = "OUT OF AMMO"
     else
        Obj120.text = countAmmo.." Bullet(s)"
     end
  
     user.answer = event.target.name
     timer.performWithDelay(750, checkForWinner)
  end
  
  -- play audio on channel 1-32 (select channel 0 for the default):
  Obj59 = audio.play( Obj55 )

  -- Obj82: randomize opponent answer (copy)
  -- generates random number between 1 and 3
  -- randomizes opponent's moves
  Enemy = math.random (1,3)
  
  if Enemy == 1 then
      opponent.answer = "SHIELD"
      enemyShield = enemyShield + 1
  elseif Enemy == 2 then
      if enemyAmmo < 1 then
         opponent.answer = "RELOAD"
         enemyAmmo = enemyAmmo + 1
         print ("Enemy Ammo = "..enemyAmmo)
     else
         opponent.answer = "GUN"
         enemyShoot = enemyShoot + 1
         enemyAmmo = enemyAmmo - 1
         print ("Enemy Ammo = "..enemyAmmo)
         print ("Enemy Shots Fired = "..enemyShoot)
     end 
  elseif Enemy == 3 then
         opponent.answer = "RELOAD"
         enemyAmmo = enemyAmmo + 1
         print ("Enemy Ammo = "..enemyAmmo)
  end

end


-- remember to move button image resources into your project folder!
Obj23 = widget.newButton({
  x = 273,
  y = 484,
  width = 88,
  height = 63,
  id = "Obj23",
  label = "",
  labelAlign = "center",
  font = "Roboto-Light",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "Reload.png",
  overFile = "ReloadPressed.png",
  onPress = Obj23OnPressHandler,
})

-- fn to handle button press on Obj26
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj26
function Obj26OnPressHandler( event )

  -- Obj28: default button event support
  -- Shield button listener
  if gameisRunning then
     print("You are defending")
     countShield = countShield + 1
     print ("Shields = "..countShield)
     user.answer = event.target.name
  end
  
  timer.performWithDelay(750, checkForWinner)
  
  -- play audio on channel 1-32 (select channel 0 for the default):
  Obj57 = audio.play( Obj56 )

  -- Obj83: randomize opponent answer (copy) (copy)
  -- generates random number between 1 and 3
  -- randomizes opponent's moves
  Enemy = math.random (1,3)
  
  if Enemy == 1 then
      opponent.answer = "SHIELD"
      enemyShield = enemyShield + 1
  elseif Enemy == 2 then
      if enemyAmmo < 1 then
         opponent.answer = "RELOAD"
         enemyAmmo = enemyAmmo + 1
         print ("Enemy Ammo = "..enemyAmmo)
     else
         opponent.answer = "GUN"
         enemyShoot = enemyShoot + 1
         enemyAmmo = enemyAmmo - 1
         print ("Enemy Ammo = "..enemyAmmo)
         print ("Enemy Shots Fired = "..enemyShoot)
     end 
  elseif Enemy == 3 then
      opponent.answer = "RELOAD"
      enemyAmmo = enemyAmmo + 1
      print ("Enemy Ammo = "..enemyAmmo)
  end

end


-- remember to move button image resources into your project folder!
Obj26 = widget.newButton({
  x = 49,
  y = 481,
  width = 113,
  height = 80,
  id = "Obj26",
  label = "",
  labelAlign = "center",
  font = "Roboto-Light",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "Shield.png",
  overFile = "ShieldPressed.png",
  onPress = Obj26OnPressHandler,
})

-- fn to handle button press on Obj29
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj29
function Obj29OnPressHandler( event )

  -- Obj31: default button event support
  -- Gun button listener
  if gameisRunning then
        -- prevents gun from being fired if user hasn't reloaded first
    if countAmmo > 0 then
        -- keeps track of shots fired
        countShoot = countShoot + 1
        -- decreases ammo when gun is fired
        countAmmo = countAmmo - 1
      if countAmmo == 0 then
        Obj120.text = "OUT OF AMMO"
      else
        Obj120.text = countAmmo
      end
        -- plays gunshot sound
        Obj58 = audio.play( Obj54 )
        print("You have shot your gun")
        print ("Shots Fired = "..countShoot)
        print ("Ammo = "..countAmmo)
        user.answer = event.target.name
  else
       print ("Please load your gun before shooting")
  end;end
  
  timer.performWithDelay(750, checkForWinner)

  -- Obj77: randomize opponent answer
  -- generates random number between 1 and 3
  -- randomizes opponent's moves
  Enemy = math.random (1,3)
  
  if Enemy == 1 then
      opponent.answer = "SHIELD"
      enemyShield = enemyShield + 1
  elseif Enemy == 2 then
      if enemyAmmo < 1 then
         opponent.answer = "RELOAD"
         enemyAmmo = enemyAmmo + 1
         print ("Enemy Ammo = "..enemyAmmo)
     else
         opponent.answer = "GUN"
         enemyShoot = enemyShoot + 1
         enemyAmmo = enemyAmmo - 1
         print ("Enemy Ammo = "..enemyAmmo)
         print ("Enemy Shots Fired = "..enemyShoot)
     end 
  elseif Enemy == 3 then
      opponent.answer = "RELOAD"
      enemyAmmo = enemyAmmo + 1
      print ("Enemy Ammo = "..enemyAmmo)
  end

end


-- remember to move button image resources into your project folder!
Obj29 = widget.newButton({
  x = 160,
  y = 474,
  width = 113,
  height = 87,
  id = "Obj29",
  label = "",
  labelAlign = "center",
  font = "Roboto-Light",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "revolver.png",
  overFile = "RevolverPressed.png",
  onPress = Obj29OnPressHandler,
})

-- button names
Obj26.name = "SHIELD"
Obj29.name = "GUN"
Obj23.name = "RELOAD"

MenuGroup = display.newGroup()
MenuGroup:insert(Obj79)
MenuGroup:insert(Obj12)
MenuGroup:insert(Obj15)
-- MenuGroup:insert(Obj58) --<< this object is not included in the generated code
-- MenuGroup:insert(Obj74) --<< this object is not included in the generated code
MenuGroup.x = 0
MenuGroup.y = 0
MenuGroup.alpha = 1.0
MenuGroup.calculations = {
  avgX = 160,
  avgY = 193,
  centerX = 160,
  centerY = 218,
  width = 326,
  height = 303
}

MenuGroup.id = "MenuGroup"

-- fn to handle events for Obj63
-- https://docs.coronalabs.com/api/library/native/showAlert.html
-- note: this fn must be positioned in the stack above Obj63
function Obj63OnShowAlertHandler( event )

  -- Obj65: default show alert event support
  if ( event.action == "clicked" ) then
     i = event.index
  if i == 1 then
     gameisRunning = false
     Obj52 = transition.to(MenuGroup, {time=1000, delay=500, alpha=1.0})
     Obj53 = transition.to(GameGroup1, {time=1000, alpha=0.0})
     print ("You have quit the game")
  else
     transition.resume(Obj44)
  end;end

end


-- fn to handle button press on Obj48
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj48
function Obj48OnPressHandler( event )

  -- Obj50: default button event support
  --stops the clouds moving
  transition.pause(CloudsGroup)
  Obj63_buttons = {"Yes","No",}
  Obj63 = native.showAlert(
    "Alert Dialog",
    "Are you sure you want to quit the game?",
    Obj63_buttons,
    Obj63OnShowAlertHandler
  )	

end


-- remember to move button image resources into your project folder!
Obj48 = widget.newButton({
  x = 34,
  y = -10,
  width = 60,
  height = 40,
  id = "Obj48",
  label = "",
  labelAlign = "center",
  font = "Helvetica Neue",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "CowboyHat.png",
  overFile = "CowboyHat.png",
  onPress = Obj48OnPressHandler,
})

Obj51_options = {
  text = "HOME",
  x = 37,
  y = 20,
  width = 60,
  height = 13,
  font = "HelveticaNeue",
  fontSize = 9,
  align = "center",
}
Obj51 = display.newText( Obj51_options )
Obj51.id = "Obj51"
Obj51:setTextColor(0.0, 0.0, 0.0, 1.0)

Obj3_options = {
  text = "MUSIC",
  x = 295,
  y = 20,
  width = 60,
  height = 13,
  font = "HelveticaNeue",
  fontSize = 9,
  align = "center",
}
Obj3 = display.newText( Obj3_options )
Obj3.id = "Obj3"
Obj3:setTextColor(0.0, 0.0, 0.0, 1.0)

function doNothing( event )
  return true

end


Obj86 = display.newRect(160, 480, 120, 100)
Obj86.id = "Obj86"
Obj86:setFillColor(0.4, 0.2, 0.0, 1.0)
Obj86.alpha = 0.1

-- image "BigCloud.png"
Obj36 = display.newImageRect( "BigCloud.png", 189, 152 )
Obj36.x = 519
Obj36.y = 62
Obj36.id = "Obj36"

-- image "BigCloud.png"
Obj41 = display.newImageRect( "BigCloud.png", 101, 101 )
Obj41.x = 805
Obj41.y = 101
Obj41.id = "Obj41"

-- image "Cloud medium.png"
Obj37 = display.newImageRect( "Cloud medium.png", 164, 152 )
Obj37.x = 404
Obj37.y = 120
Obj37.id = "Obj37"

-- image "Cloud medium.png"
Obj40 = display.newImageRect( "Cloud medium.png", 88, 63 )
Obj40.x = 739
Obj40.y = 61
Obj40.id = "Obj40"

-- image "CloudSmall.png"
Obj38 = display.newImageRect( "CloudSmall.png", 114, 88 )
Obj38.x = 271
Obj38.y = 36
Obj38.id = "Obj38"

-- image "CloudSmall.png"
Obj39 = display.newImageRect( "CloudSmall.png", 51, 51 )
Obj39.x = 659
Obj39.y = 132
Obj39.id = "Obj39"

-- image "CloudSmall.png"
Obj43 = display.newImageRect( "CloudSmall.png", 51, 51 )
Obj43.x = 967
Obj43.y = 65
Obj43.id = "Obj43"

-- image "CloudSmall.png"
Obj42 = display.newImageRect( "CloudSmall.png", 114, 101 )
Obj42.x = 880
Obj42.y = 44
Obj42.id = "Obj42"

-- fn to handle button press on Obj109
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj109
function Obj109OnPressHandler( event )

  -- Obj111: restart
  -- restarts the game
  Obj15OnPressHandler( )
  quit_out = transition.to(Obj112, {time=500, delay = 0, alpha=0.0})
  continue_out = transition.to(Obj109, {time=500, delay = 0, alpha=0.0})

end


-- remember to move button image resources into your project folder!
Obj109 = widget.newButton({
  x = 160,
  y = 180,
  width = 200,
  height = 114,
  id = "Obj109",
  label = "",
  labelAlign = "center",
  font = "Helvetica Neue",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "ContinuePlayin.png",
  overFile = "ContinuePlayin.png",
  onPress = Obj109OnPressHandler,
})
Obj109.alpha = 0.0

-- fn to handle button press on Obj112
-- https://docs.coronalabs.com/api/library/widget/newButton.html
-- note: this fn must be positioned in the stack above Obj112
function Obj112OnPressHandler( event )

  -- Obj114: quit
  Obj12OnPressHandler( )
  quit_out = transition.to(Obj112, {time=500, delay = 0, alpha=0.0})
  continue_out = transition.to(Obj109, {time=500, delay = 0, alpha=0.0})

end


-- remember to move button image resources into your project folder!
Obj112 = widget.newButton({
  x = 160,
  y = 310,
  width = 200,
  height = 114,
  id = "Obj112",
  label = "",
  labelAlign = "center",
  font = "Helvetica Neue",
  fontSize = 22,
  labelColor = { default = {0.25, 0.54, 0.87, 1.0}, over = {0.17, 0.37, 0.61, 1.0} },
  defaultFile = "QuitButton.png",
  overFile = "QuitButton.png",
  onPress = Obj112OnPressHandler,
})
Obj112.alpha = 0.0

function checkForWinner( )

  -- Obj76: win/lose logic
  if user.answer == "SHIELD" and opponent.answer == "GUN" then
  
    print ("You deflected the gunshot") 
    Obj78.text = "You deflected the gunshot"
  
  elseif user.answer == "GUN" and opponent.answer == "RELOAD" then
    opponent.lives = opponent.lives - 1
    print (opponent.name.." has lost a life")
    Obj78.text = opponent.name.." has lost a life"
  
       if opponent.lives == 0 then
         Obj78.text = "Hombre wins!" 
         gameOver = true
         print ("You shot and killed "..opponent.name)
       end
  
  elseif user.answer == "RELOAD" and opponent.answer == "SHIELD" then
    print ("Keep Trying!")
    Obj78.text = opponent.name.." chose "..opponent.answer
  
  elseif opponent.answer == "SHIELD" and user.answer == "GUN" then
     print ("Your shot was deflected")
     Obj78.text = "Your shot was deflected"
  
  elseif opponent.answer == "GUN" and user.answer == "RELOAD" then
     user.lives = user.lives - 1
     print ("You have lost a life")
     Obj78.text = "You have lost a life"
         if user.lives == 0 then
            print (opponent.name.. " shot and killed you. You are dead.")
            Obj78.text = "You lose!" 
            gameOver = true
         end
  
  elseif opponent.answer == "RELOAD" and user.answer == "SHIELD" then
    print ("Keep Trying!")
    Obj78.text = opponent.name.." chose "..opponent.answer
  
  else
     -- tie
     print ("DRAW!")
     Obj78.text = "DRAW! BOTH CHOSE " .. user.answer
  end
  
  -- prevents user from shooting without reloading first
  if countAmmo < 1 then
     Obj86.isVisible = true
     Obj86:addEventListener("tap", doNothing)
     Obj86:addEventListener("touch", doNothing)
  else
     Obj86.isVisible = false
  end
  
  print ("You chose "..user.answer)
  print (opponent.name.." chose "..opponent.answer)
  Obj102.text = opponent.name..": "..opponent.lives.." Lives"
  Obj100.text = user.name..": "..user.lives.." Lives"

  -- Obj119: game over
  if gameOver and Obj78.text == "Hombre wins!" then
     if opponent.name == "Bandido" then
  
        alive1 = transition.to(Obj21, {time = 300, delay = 200, alpha = 0.0})
        dead1 = transition.to(Obj97, {time = 300, delay = 400, alpha = 1.0})
  
     elseif opponent.name == "Outlaw" then
  
       alive2 = transition.to(Obj81, {time = 300, delay = 200, alpha = 0.0})
       dead2 = transition.to(Obj98, {time = 300, delay = 400, alpha = 1.0})
  
     elseif opponent.name == "Raggedy Carlson" then
  
       alive3 = transition.to(Obj93, {time = 300, delay = 200, alpha = 0.0})
       dead3 = transition.to(Obj99, {time = 300, delay = 400, alpha = 1.0})
  
     end
  
     game_out = transition.to(GameGroup1, {time = 1000, delay = 2000, alpha = 0.0})
     quit_in = transition.to(Obj112, {time=1000, delay = 2500, alpha=1.0})
     continue_in = transition.to(Obj109, {time=1000, delay = 2500, alpha=1.0})
  
  end
  
  if gameOver then
     game_out = transition.to(GameGroup1, {time = 1000, delay = 2000, alpha = 0.0})
     quit_in = transition.to(Obj112, {time=1000, delay = 2500, alpha=1.0})
  end

end


CloudsGroup = display.newGroup()
-- CloudsGroup:insert(Obj58) --<< this object is not included in the generated code
CloudsGroup:insert(Obj36)
CloudsGroup:insert(Obj41)
CloudsGroup:insert(Obj37)
CloudsGroup:insert(Obj40)
CloudsGroup:insert(Obj38)
CloudsGroup:insert(Obj39)
CloudsGroup:insert(Obj43)
CloudsGroup:insert(Obj42)
-- CloudsGroup:insert(Obj74) --<< this object is not included in the generated code
CloudsGroup.x = 0
CloudsGroup.y = 0
CloudsGroup.alpha = 1.0
CloudsGroup.calculations = {
  avgX = 655,
  avgY = 77,
  centerX = 603,
  centerY = 91,
  width = 778,
  height = 210
}

CloudsGroup.id = "CloudsGroup"
CloudsGroup.isVisible = false

GameGroup1 = display.newGroup()
GameGroup1:insert(Obj78)
GameGroup1:insert(Obj100)
GameGroup1:insert(Obj102)
GameGroup1:insert(Obj97)
GameGroup1:insert(Obj98)
GameGroup1:insert(Obj99)
GameGroup1:insert(Obj21)
GameGroup1:insert(Obj81)
GameGroup1:insert(Obj93)
GameGroup1:insert(Obj22)
GameGroup1:insert(Obj120)
GameGroup1:insert(Obj23)
GameGroup1:insert(Obj26)
-- GameGroup1:insert(Obj58) --<< this object is not included in the generated code
GameGroup1:insert(Obj29)
GameGroup1:insert(Obj48)
GameGroup1:insert(Obj51)
GameGroup1:insert(Obj86)
GameGroup1:insert(CloudsGroup)
-- GameGroup1:insert(Obj74) --<< this object is not included in the generated code
GameGroup1.x = 0
GameGroup1.y = 0
GameGroup1.alpha = 0.0
GameGroup1.calculations = {
  avgX = 154,
  avgY = 306,
  centerX = 169,
  centerY = 250,
  width = 392,
  height = 560
}

GameGroup1.id = "GameGroup1"
GameGroup1.alpha = 0.0

-- image "mute.png"
Obj72 = display.newImageRect( "mute.png", 27, 40 )
Obj72.x = 297
Obj72.y = -10
Obj72.id = "Obj72"

-- image "mute_pressed.png"
Obj73 = display.newImageRect( "mute_pressed.png", 27, 35 )
Obj73.x = 295
Obj73.y = -10
Obj73.id = "Obj73"
Obj73.isVisible = false

-- fn to handle switch events for Obj69
-- https://docs.coronalabs.com/api/library/widget/newSwitch.html
-- note: this fn must be positioned in the stack above Obj69
function Obj69OnReleaseHandler( event )

  -- Obj71: default switch event support
  s = event.target
  if s.isOn then
    Obj73.isVisible = false
    Obj72.isVisible = true
    -- plays background music
    sound = audio.resume (Obj67)
  else
    Obj73.isVisible = true
    Obj72.isVisible = false
    -- pauses background music
    Obj74 = audio.pause( Obj67 )
  end

end

Obj69 = widget.newSwitch({
  style = "checkbox",
  id = "Obj69",
  x = 298,
  y = -10,
  initialSwitchState = true,
  onRelease = Obj69OnReleaseHandler,
})
Obj69.alpha = 0.01

-- included toBack() / toFront() calls processed in stack order:
Obj78:toFront()
Obj79:toFront()
Obj6:toFront()
Obj21:toFront()
Obj81:toFront()
Obj93:toFront()
Obj3:toFront()
GameGroup1:toFront()
Obj72:toFront()
Obj73:toFront()